### ISSUE TITLE
source

### ISSUE THREAD

**Issue by knoxh** [knoxh/Twitter#6]
I was able to finish the functions and separate the function calls from the function bodies (not sure what term to use), but when I call the functions in function_call.R, I get an error. Do I have to put any information on the rtweet.R file so it connects it to function_call.R? function_call.R just sources rtweet.R and calls the functions. Does more have to be added? Thank you @gdancik

**Comment by gdancik** [comment]
You should just need to source _retweet.R_ from within _function_call.R_. But _function_call.R_ is not currently on Github. If you add that to your Github repository, I can take a closer look.
